### ISSUE TITLE
Broken changes for Asterisk 17.5.1

### ISSUE THREAD

**Issue by zloidemon** [alphacep/vosk-asterisk#9]
This is c551a1d7b83b50f5eb964aba120cddf23c443ab9 commit. After update without fixed websocket module doesn't work.

```
[Jul 12 12:24:23] NOTICE[558088][C-00000001]: res_speech_vosk.c:83 vosk_recog_create: (vosk) Create speech resource ws://127.0.0.1:2700
[Jul 12 12:24:23] NOTICE[558088][C-00000001]: res_speech_vosk.c:91 vosk_recog_create: (vosk) Created speech resource result 0
    -- Executing [1@internal-r:4] SpeechBackground("PJSIP/6002-00000000", "hello") in new stack
[Jul 12 12:24:23] NOTICE[558088][C-00000001]: res_speech_vosk.c:201 vosk_recog_start: (vosk) Start recognition
[Jul 12 12:24:23] NOTICE[558088][C-00000001]: res_speech_vosk.c:182 vosk_recog_write: (vosk) Got error result -1
[Jul 12 12:24:26] NOTICE[558088][C-00000001]: res_speech_vosk.c:98 vosk_recog_destroy: (vosk) Destroy speech resource
```

vosk-server

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/server.py", line 169, in handler
    yield from self.ws_handler(self, path)
  File "./asr_server.py", line 55, in recognize
    message = await websocket.recv()
  File "/usr/lib/python3/dist-packages/websockets/protocol.py", line 434, in recv
    yield from self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/protocol.py", line 658, in ensure_open
    ) from self.transfer_data_exc
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason
```

**Comment by nshmyrev** [comment]
You need https://github.com/asterisk/asterisk/tree/17.6 I presume.
